---
- name: Set up Master Node on Kubernetes
  hosts: Master
  become: true
  roles:
    - setup-master-node

- name: Set up Worker Node on Kubernetes
  hosts: Worker
  become: true
  roles:
    - setup-worker-node

- name: Set labels for Worker Node
  hosts: Master
  become: true
  roles:
    - set-label
  
- name: Apply Calico and Metric Server
  hosts: Master
  become: true
  roles:
    - calico-metric